schedules:
  - title: "[Mobisys'23] ElasticTrainer: Speeding Up On-Device Training with Runtime Elastic Tensor Selection"
    conf: "Mobisys'23"
    presenter: Chenyu Lu
    date: June 29, 2023.
    links:
      - title: TecentMeeting
        url: https://meeting.tencent.com/dm/kBz2Zw9Ne8sx
      - title: Slides
        url: /slides/ElasticTrainer.pdf
  - title: "[ASPLOS'22] INFless: A Native Serverless System for Low-Latency, High-Throughput Inference"
    conf: "ASPLOS'22"
    presenter: Guangtong Li
    date: June 15, 2023.
    links:
      - title: TecentMeeting
        url: https://meeting.tencent.com/dm/tcI8MDYCn5zO
      - title: Slides
        url: /slides/INFless.pdf
  - title: "[Mobisys'23] ConvReLU++: Reference-based Lossless Acceleration of Conv-ReLU Operations on Mobile CPU"
    conf: "Mobisys'23"
    presenter: Ye Wan
    date: June 8, 2023.
    links:
      - title: TecentMeeting
        url: https://meeting.tencent.com/dm/GIZlZUew5kj5
      - title: Slides
        url: /slides/ConvRelu++.pdf
  - title: "[ASPLOS'23] BeeHive: Sub-second Elasticity for Web Services with Semi-FaaS Execution"
    conf: "ASPLOS'23"
    presenter: Haodong Tian
    date: June 1, 2023.
    links:
      - title: TecentMeeting
        url: https://meeting.tencent.com/dm/GIZlZUew5kj5
      - title: Slides
        url: /slides/BeeHive.pdf
  - title: "[MobiSys'23] Understanding and Optimizing Deep Learning Cold-Start Latency on Edge Devices"
    conf: "MobiSys'23"
    presenter: Mengyang Liu
    date: May 25, 2023.
    links:
      - title: TecentMeeting
        url: https://meeting.tencent.com/dm/vtnLMBunSfXU
      - title: Slides
        url: /slides/NNV12.pdf
  - title: "[NSDI'23] ModelKeeper: Accelerating DNN Training via Automated Training Warmup"
    conf: "NSDI'23"
    presenter: Chenyu Lu
    date: Apr 13, 2023.
    links:
      - title: TecentMeeting
        url: https://meeting.tencent.com/dm/6fPisSgvNOXv
      - title: Slides
        url: /slides/ModelKeeper.pdf
  - title: "[ASPLOS'22] AStitch: Enabling a New Multi-dimensional Optimization Space for Memory-Intensive ML Training and Inference on Modern SIMT Architectures"
    conf: "ASPLOS'22"
    presenter: Guangtong Li
    date: Mar 30, 2023.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/yNGi2Nxl94go
      - title: Slides
        url: /slides/AStitch.pdf
  - title: "[Sensys'22] Hyperion: A Generic and Distributed Mobile Offloading Framework on OpenCL"
    conf: "Sensys'22"
    presenter: Ye Wan
    date: Mar 23, 2023.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/81KneO3hsY4j
      - title: Slides
        url: /slides/Hyperion.pdf
  - title: "[OSDI'22] ROLLER: Fast and Efficient Tensor Compilation for Deep Learning"
    conf: "OSDI'22"
    presenter: Haodong Tian
    date: Mar 16, 2023.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/zqo5C6KTLUDi
      - title: Slides
        url: /slides/ROLLER.pdf

  - title: "[ASPLOS'23] TLP: A Deep Learning-Based Cost Model for Tensor Program Tuning"
    conf: "ASPLOS'23"
    presenter: Mengyang Liu
    date: Mar 9, 2023.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/gF9Ft3uO69PR
      - title: Slides
        url: /slides/TLP.pdf
  - title: "[SenSys'22] BlastNet: Exploiting Duo-Blocks for Cross-Processor Real-Time DNN Inference"
    conf: "SenSys'22"
    presenter: Chenyu Lu
    date: Feb 27, 2023.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/m37eOiuvurKe
      - title: Slides
        url: /slides/BlastNet.pdf
  - title: "[ATC'22] Cachew: Machine Learning Input Data Processing as a Service"
    conf: "ATC'22"
    presenter: Guangtong Li
    date: Feb 20, 2023.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/VMAxl6WX5SDt
      - title: Slides
        url: /slides/CacheW.pdf
  - title: "[ATC'22] Soter: Guarding Black-box Inference for General Neural Networks at the Edge"
    conf: "ATC'22"
    presenter: Ye Wan
    date: Feb 13, 2023.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/XamoSoFq9K08
      - title: Slides
        url: /slides/SOTER.pdf
  - title: "[OSDI'22] Microsecond-scale Preemption for Concurrent GPU-accelerated DNN Inference"
    conf: "OSDI'22"
    presenter: Mengyang Liu
    date: Feb 7, 2023.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/oL97GlMJEADM
      - title: Slides
        url: /slides/REEF.pdf

  - title: "[ATC'22] Tetris: Memory-efficient Serverless Inference through Tensor Sharing"
    conf: "ATC'22"
    presenter: Haodong Tian
    date: Jan 30, 2023.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/rYCLuoA7EVSf
      - title: Slides
        url: /slides/Tetris.pdf

  - title: "[ATC'22] Serving Heterogeneous Machine Learning Models on Multi-GPU Servers with Spatio-Temporal Sharing"
    conf: "ATC'22"
    presenter: Chenyu Lu
    date: Jan 16, 2023.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/QItk9sCtnRMl
      - title: Slides
        url: /slides/Gpulet.pdf

  - title: "[ATC'22] Campo: Cost-Aware Performance Optimization for Mixed-Precision Neural Network Training"
    conf: "ATC'22"
    presenter: Guangtong Li
    date: Jan 9, 2023.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/3wejGnobNOHR
      - title: Slides
        url: /slides/Campo.pdf

  - title: "[MobiSys'22] Melon: Breaking the Memory Wall for Resource-Efficient On-Device Machine Learning"
    conf: "MobiSys'22"
    presenter: Ye Wan
    date: December 26, 2022.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/BkcWtYkIeqC3
      - title: Slides
        url: /slides/Melon.pdf


  - title: "[MobiCom'22] Romou: rapidly generate high-performance tensor kernels for mobile GPUs"
    conf: "MobiCom'22"
    presenter: Mengyang Liu
    date: December 19, 2022.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/uS6xPdn9NzCi
      - title: Slides
        url: /slides/Romou.pdf

  - title: "[MobiCom'22] Real-time neural network inference on extremely weak devices: agile offloading with explainable AI"
    conf: "MobiCom'22"
    presenter: Chenyu Lu
    date: December 5, 2022.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/1BKlQNoChOlt
      - title: Slides
        url: /slides/AgileNN.pdf

  - title: "[MobiSys'22] Band: coordinated multi-DNN inference on heterogeneous mobile processors"
    conf: "MobiSys'22"
    presenter: Guangtong Li
    date: November 28, 2022.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/TUIsg858C5VV
      - title: Slides
        url: /slides/BAND.pdf

  - title: "[MobiSys'22] CoDL: Efficient CPU-GPU Co-Execution for Deep Learning Inference on Mobile Devices"
    conf: "MobiSys'22"
    presenter: Ye Wan
    date: November 21, 2022.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/ZMCR9ItoDoFt
      - title: Slides
        url: /slides/CoDL.pdf

  - title: "[MobiSys'21] nn-Meter: Towards Accurate Latency Prediction of Deep-Learning Model Inference on Diverse Edge Devices"
    conf: "MobiSys'21"
    presenter: Mengyang Liu
    date: November 14, 2022.
    links:
      - title: TencentMeeting
        url: https://meeting.tencent.com/dm/6r5oKfu8QCZO
      - title: Slides
        url: /slides/nn-Meter.pdf

upcomings:
  - "Mengyang Liu will present an OSDI'22 paper on Monday, Feb 6, 2023, at 7:00 p.m. (GMT+8)."

# Refer to https://fontawesome.com/v4/icons/ for an ideal icon.
# The default icon is fa-thumb-tack.
links:
  # - title: Paper Pool is here.
  #   url: https://jhagyscvrs.feishu.cn/sheets/shtcnXvN4tNwKVLO9K3dt2QgBae?sheet=18ce4c
  #   icon: fa-paperclip

  # - title: How to contribute to this website?
  #   url: https://github.com/SEU-ESG/SEU-ESG.github.io/blob/master/How-To-Update.md
  #   icon: fa-github

  - title: Upload a new schedule.
    url: https://github.com/lgdamefans/lgdamefans.github.io/edit/master/configs/config.yml
    icon: fa-pencil

# Refer to https://www.w3schools.com/w3css/w3css_colors.asp for an ideal color.
# The default primary color is teal, and the default accent color is pale-green.
layout:
  schedulesPerPage: 5
  primaryColor: teal
  accentColor: light-gray

global:
  header: MintLab @ UESTC
  footer: 2023 Mintlab. Powered by Jekyll and GitHub Pages.
