schedules:
  # - title: "[Mobisys'23] ElasticTrainer: Speeding Up On-Device Training with Runtime Elastic Tensor Selection"
  #   conf: "Mobisys'23"
  #   presenter: Chenyu Lu
  #   date: June 29, 2023.
  #   links:
  #     - title: TecentMeeting
  #       url: https://meeting.tencent.com/dm/kBz2Zw9Ne8sx
  #     - title: Slides
  #       url: /slides/ElasticTrainer.pdf
  
upcomings:
  - "Next seminar will present on Friday, Jul 21, 2023, at 3:00 p.m. (GMT+8)."

# Refer to https://fontawesome.com/v4/icons/ for an ideal icon.
# The default icon is fa-thumb-tack.
links:
  # - title: Paper Pool is here.
  #   url: https://jhagyscvrs.feishu.cn/sheets/shtcnXvN4tNwKVLO9K3dt2QgBae?sheet=18ce4c
  #   icon: fa-paperclip

  # - title: How to contribute to this website?
  #   url: https://github.com/SEU-ESG/SEU-ESG.github.io/blob/master/How-To-Update.md
  #   icon: fa-github

  - title: Upload a new schedule.
    url: https://github.com/lgdamefans/lgdamefans.github.io/edit/master/configs/config.yml
    icon: fa-pencil

# Refer to https://www.w3schools.com/w3css/w3css_colors.asp for an ideal color.
# The default primary color is teal, and the default accent color is pale-green.
layout:
  schedulesPerPage: 5
  primaryColor: teal
  accentColor: light-gray

global:
  header: MintLab @ UESTC
  footer: 2023 Mintlab. Powered by Jekyll and GitHub Pages.
